export const ConnectionStep = Object.freeze({
  ATTEMPT_STARTED: 'AttemptStarted',
  ANNOUNCE_SENT: 'AnnounceSent',
  ANNOUNCE_RECEIVED: 'AnnounceReceived',
  OFFER_REQUESTED: 'OfferRequested',
  OFFER_CREATING: 'OfferCreating',
  OFFER_CREATED: 'OfferCreated',
  OFFER_SUPPRESSED: 'OfferSuppressed',
  REPLACING_CONNECTION: 'ReplacingConnection',
  OFFER_SENT: 'OfferSent',
  OFFER_RECEIVED: 'OfferReceived',
  ANSWER_CREATING: 'AnswerCreating',
  ANSWER_SENT: 'AnswerSent',
  ANSWER_RECEIVED: 'AnswerReceived',
  SIGNAL_RELAYED: 'SignalRelayed',
  ROUTE_AVAILABLE: 'RouteAvailable',
});
